export default ({

  LOGIN:                         'LOGIN',
  LOGIN_ERROR:                   'LOGIN_ERROR',
  LOGOUT:                        'LOGOUT',

  DECREMENT_COUNTDOWN:           'DECREMENT_COUNTDOWN',
  RESET_COUNTDOWN:               'RESET_COUNTDOWN',

  ADD_DECK:                      'ADD_DECK',
  FETCHING_DECK:                 'FETCHING_DECK',
  NOT_FOUND_DECK:                'NOT_FOUND_DECK',
  ERROR_FETCHING_DECK:           'ERROR_FETCHING_DECK',

  FETCHING_GAME_TITLES:          'FETCHING_GAME_TITLES',
  SET_GAME_TITLES:               'SET_GAME_TITLES',
  ERROR_FETCHING_GAME_TITLES:    'ERROR_FETCHING_GAME_TITLES',

  OPEN_NAV_OPTIONS:              'OPEN_NAV_OPTIONS',
  CLOSE_NAV_OPTIONS:             'CLOSE_NAV_OPTIONS',

  FETCHING_LIVE_QUESTIONS:       'FETCHING_LIVE_QUESTIONS',
  SET_LIVE_QUESTIONS:            'SET_LIVE_QUESTIONS',
  NOT_FOUND_LIVE_QUESTIONS:      'NOT_FOUND_LIVE_QUESTIONS',
  ERROR_FETCHING_LIVE_QUESTIONS: 'ERROR_FETCHING_LIVE_QUESTIONS',

  FETCHING_RECENT_ANSWERS:       'FETCHING_RECENT_ANSWERS',
  SET_RECENT_ANSWERS:            'SET_RECENT_ANSWERS',
  NOT_FOUND_RECENT_ANSWERS:      'NOT_FOUND_RECENT_ANSWERS',
  ERROR_FETCHING_RECENT_ANSWERS: 'ERROR_FETCHING_RECENT_ANSWERS',

  FETCHING_ALLTIME_STATS:        'FETCHING_ALLTIME_STATS',
  SET_ALLTIME_STATS:             'SET_ALLTIME_STATS',
  NOT_FOUND_ALLTIME_STATS:       'NOT_FOUND_ALLTIME_STATS',
  ERROR_FETCHING_ALLTIME_STATS:  'ERROR_FETCHING_ALLTIME_STATS',

  FETCHING_MONTHLY_STATS:        'FETCHING_MONTHLY_STATS',
  SET_MONTHLY_STATS:             'SET_MONTHLY_STATS',
  NOT_FOUND_MONTHLY_STATS:       'NOT_FOUND_MONTHLY_STATS',
  ERROR_FETCHING_MONTHLY_STATS:  'ERROR_FETCHING_MONTHLY_STATS',

  FETCHING_WEEKLY_STATS:         'FETCHING_WEEKLY_STATS',
  SET_WEEKLY_STATS:              'SET_WEEKLY_STATS',
  NOT_FOUND_WEEKLY_STATS:        'NOT_FOUND_WEEKLY_STATS',
  ERROR_FETCHING_WEEKLY_STATS:   'ERROR_FETCHING_WEEKLY_STATS',

  FETCHING_EARNED_CARDS:         'FETCHING_EARNED_CARDS',
  SET_EARNED_CARDS:              'SET_EARNED_CARDS',
  NOT_FOUND_EARNED_CARDS:        'NOT_FOUND_EARNED_CARDS',
  ERROR_FETCHING_EARNED_CARDS:   'ERROR_FETCHING_EARNED_CARDS',

  FETCHING_FOCUSED_USER:         'FETCHING_FOCUSED_USER',
  SET_FOCUSED_USER:              'SET_FOCUSED_USER',
  NOT_FOUND_FOCUSED_USER:        'NOT_FOUND_FOCUSED_USER',
  ERROR_FETCHING_FOCUSED_USER:   'ERROR_FETCHING_FOCUSED_USER',

  SET_SCORE_VIEW:                'SET_SCORE_VIEW',
  SET_SEARCH_QUERY:              'SET_SEARCH_QUERY'

})
