export default ({

  AUTH_TRANSITION:                 'AUTH_TRANSITION',
  LOGIN:                           'LOGIN',
  LOGIN_ERROR:                     'LOGIN_ERROR',
  LOGOUT:                          'LOGOUT',

  DECREMENT_COUNTDOWN:             'DECREMENT_COUNTDOWN',
  RESET_COUNTDOWN:                 'RESET_COUNTDOWN',

  ADD_DECK:                        'ADD_DECK',
  FETCHING_DECK:                   'FETCHING_DECK',
  NOT_FOUND_DECK:                  'NOT_FOUND_DECK',
  ERROR_FETCHING_DECK:             'ERROR_FETCHING_DECK',

  FETCHING_DECK_TITLES:            'FETCHING_DECK_TITLES',
  SET_DECK_TITLES:                 'SET_DECK_TITLES',
  ERROR_FETCHING_DECK_TITLES:      'ERROR_FETCHING_DECK_TITLES',

  OPEN_NAV_OPTIONS:                'OPEN_NAV_OPTIONS',
  CLOSE_NAV_OPTIONS:               'CLOSE_NAV_OPTIONS',

  SET_CARD_VIEW:                   'SET_CARD_VIEW',
  SET_SCORE_VIEW:                  'SET_SCORE_VIEW',
  SET_SEARCH_QUERY:                'SET_SEARCH_QUERY',

  FETCHING_LIVE_QUESTIONS:         'FETCHING_LIVE_QUESTIONS',
  SET_LIVE_QUESTIONS:              'SET_LIVE_QUESTIONS',
  NOT_FOUND_LIVE_QUESTIONS:        'NOT_FOUND_LIVE_QUESTIONS',
  ERROR_FETCHING_LIVE_QUESTIONS:   'ERROR_FETCHING_LIVE_QUESTIONS',

  FETCHING_RECENT_ANSWERS:         'FETCHING_RECENT_ANSWERS',
  SET_RECENT_ANSWERS:              'SET_RECENT_ANSWERS',
  NOT_FOUND_RECENT_ANSWERS:        'NOT_FOUND_RECENT_ANSWERS',
  ERROR_FETCHING_RECENT_ANSWERS:   'ERROR_FETCHING_RECENT_ANSWERS',

  FETCHING_ALLTIME_STATS:          'FETCHING_ALLTIME_STATS',
  SET_ALLTIME_STATS:               'SET_ALLTIME_STATS',
  NOT_FOUND_ALLTIME_STATS:         'NOT_FOUND_ALLTIME_STATS',
  ERROR_FETCHING_ALLTIME_STATS:    'ERROR_FETCHING_ALLTIME_STATS',

  FETCHING_MONTHLY_STATS:          'FETCHING_MONTHLY_STATS',
  SET_MONTHLY_STATS:               'SET_MONTHLY_STATS',
  NOT_FOUND_MONTHLY_STATS:         'NOT_FOUND_MONTHLY_STATS',
  ERROR_FETCHING_MONTHLY_STATS:    'ERROR_FETCHING_MONTHLY_STATS',

  FETCHING_WEEKLY_STATS:           'FETCHING_WEEKLY_STATS',
  SET_WEEKLY_STATS:                'SET_WEEKLY_STATS',
  NOT_FOUND_WEEKLY_STATS:          'NOT_FOUND_WEEKLY_STATS',
  ERROR_FETCHING_WEEKLY_STATS:     'ERROR_FETCHING_WEEKLY_STATS',

  FETCHING_FOCUSED_USER:           'FETCHING_FOCUSED_USER',
  SET_FOCUSED_USER:                'SET_FOCUSED_USER',
  NOT_FOUND_FOCUSED_USER:          'NOT_FOUND_FOCUSED_USER',
  ERROR_FETCHING_FOCUSED_USER:     'ERROR_FETCHING_FOCUSED_USER',

  FETCHING_CORRECT_CARDS:          'FETCHING_CORRECT_CARDS',
  SET_CORRECT_CARDS:               'SET_CORRECT_CARDS',
  NOT_FOUND_CORRECT_CARDS:         'NOT_FOUND_CORRECT_CARDS',
  ERROR_FETCHING_CORRECT_CARDS:    'ERROR_FETCHING_CORRECT_CARDS',

  FETCHING_INCORRECT_CARDS:        'FETCHING_INCORRECT_CARDS',
  SET_INCORRECT_CARDS:             'SET_INCORRECT_CARDS',
  NOT_FOUND_INCORRECT_CARDS:       'NOT_FOUND_INCORRECT_CARDS',
  ERROR_FETCHING_INCORRECT_CARDS:  'ERROR_FETCHING_INCORRECT_CARDS',

  FETCHING_UNANSWERED_CARDS:       'FETCHING_UNANSWERED_CARDS',
  SET_UNANSWERED_CARDS:            'SET_UNANSWERED_CARDS',
  NOT_FOUND_UNANSWERED_CARDS:      'NOT_FOUND_UNANSWERED_CARDS',
  ERROR_FETCHING_UNANSWERED_CARDS: 'ERROR_FETCHING_UNANSWERED_CARDS'


})
