export default ({

  INITIAL_STATE:  'INITIAL_STATE',
  FETCHING:       'FETCHING',
  NOT_FOUND:      'NOT_FOUND',
  RESOLVED:       'RESOLVED',
  ERROR:          'ERROR',
  ERROR_FETCHING: 'ERROR_FETCHING',

  LOGGED_IN:      'LOGGED_IN',
  LOGGED_OUT:     'LOGGED_OUT'

})
